# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CO79ljwXlUtP-4WkCVel-CATgihDpHlj
"""

import matplotlib.pyplot as plt

x = np.arange(-2*np.pi,2*np.pi,0.01)
y = np.sin(3*x)/x
plt.plot(x,y)
plt.show()

index = [0,1,2,3,4]
values = [5,7,3,4,6]
plt.bar(index,values)
plt.show()

plt.plot([1, 5, 10, 15, 20], [1, 7, 3, 5, 11])
plt.show()

import math
math.e

math.pi

res = 1
for i in range(17):
  res *= (i+1)
  i += 1
print(res,i)

n = 17
memory = 32
for i in range(1,33):
  if n % i == 0 and memory % i == 0:
    print(i)

from matplotlib.patches import Circle, Wedge, Polygon, Ellipse, Arc, Path, PathPatch,Rectangle
from matplotlib.patches import  Circle

import matplotlib.pyplot as plt
import numpy as np
plt.xlim(0, 30)

plt.ylim(0, 30)
ax = plt.gca()

ellipse = Ellipse((12, 0), 14, 20, facecolor = "#c4a963",ec="black",lw = 1 ) 
ax.add_patch (ellipse)
polygon = Polygon([(10.5, 2.5), (11.5, 5), (12, 2.5)], facecolor = "#a78b50",ec="black",lw = 1 )
ax.add_patch (polygon)
polygon1 = Polygon([(12, 2.5), (13, 5), (13.5, 2.5)], facecolor = "#a78b50",ec="black",lw = 1 )
ax.add_patch (polygon1)


ellipse1 = Ellipse((12, 1), 4, 5, facecolor = "#a78b49",ec="black",lw = 1 ) 
ax.add_patch (ellipse1)

ellipse11 = Ellipse((11.5, 2), 0.5, 0.1, facecolor = "black") 
ax.add_patch (ellipse11)
ellipse12 = Ellipse((12.5, 2), 0.5, 0.1, facecolor = "black") 
ax.add_patch (ellipse12)
wedge = Wedge((12, 0.05), 0.8, 0, 180, fc="#6b5a31")
ax.add_patch (wedge)
ellipse123 = Ellipse((12, 0.4), 1, 0.5, facecolor = "#40351c") 
ax.add_patch (ellipse123)
wedge1 = Wedge((12, 0.3), 0.2, 0.5, 180, fc="#d91646")
ax.add_patch (wedge1)

ellipse2 = Ellipse((7, 0), 2, 3, facecolor = "#a78b49",ec="black",lw = 1 ) 
ax.add_patch (ellipse2)
ellipse3 = Ellipse((17, 0), 2, 3, facecolor = "#a78b49",ec="black",lw = 1 ) 
ax.add_patch (ellipse3)
arc = Arc((4, 2), 6, 4, 0, 40, 200)
ax.add_patch (arc)
plt.show()